# Generated by Django 4.1 on 2022-08-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y_%m/'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
